---
version: 1
labels:
  - label: "TestLabel"
    title: ".*"
  - label: "TestFileMatch"
    files: 
    - "cmd\\/.*.go"
    - "pkg\\/.*.go"
  - label: "TestTypePullRequest"
    type: "pull_request"
  - label: "TestTypeIssue"
    type: "issue"
